import uuid
import pytest
import pytest_asyncio
from httpx import AsyncClient

from app.db.session import AsyncSessionLocal
from app.repositories.user import user_repository


@pytest_asyncio.fixture
async def audit_superuser_headers(async_client: AsyncClient):
    """
    Fixture registering a superuser and returning Bearer authorization headers.
    """
    unique_id = uuid.uuid4().hex[:6]
    email = f"superaudit_{unique_id}@example.com"
    username = f"superaudit_{unique_id}"

    reg_payload = {
        "full_name": "Super Audit Admin",
        "email": email,
        "username": username,
        "password": "SuperPassword123!",
    }
    reg_resp = await async_client.post("/auth/register", json=reg_payload)
    user_id = uuid.UUID(reg_resp.json()["id"])

    # Mark user as superuser in DB
    async with AsyncSessionLocal() as session:
        user = await user_repository.get_by_id(session, user_id)
        if user:
            user.is_superuser = True
            await session.commit()

    login_resp = await async_client.post("/auth/login", json={
        "username_or_email": email,
        "password": "SuperPassword123!",
    })
    token = login_resp.json()["access_token"]
    return {"Authorization": f"Bearer {token}"}


@pytest_asyncio.fixture
async def audit_regular_user_headers(async_client: AsyncClient):
    """
    Fixture registering a regular user and returning Bearer authorization headers.
    """
    unique_id = uuid.uuid4().hex[:6]
    email = f"regularaudit_{unique_id}@example.com"
    username = f"regularaudit_{unique_id}"

    reg_payload = {
        "full_name": "Regular Audit User",
        "email": email,
        "username": username,
        "password": "RegularPassword123!",
    }
    await async_client.post("/auth/register", json=reg_payload)
    login_resp = await async_client.post("/auth/login", json={
        "username_or_email": email,
        "password": "RegularPassword123!",
    })
    token = login_resp.json()["access_token"]
    return {"Authorization": f"Bearer {token}"}


@pytest.mark.asyncio
async def test_request_id_middleware(async_client: AsyncClient):
    """
    Test that every HTTP response includes X-Request-ID header generated by middleware.
    """
    response = await async_client.get("/health")
    assert response.status_code == 200
    assert "x-request-id" in response.headers
    assert len(response.headers["x-request-id"]) > 0


@pytest.mark.asyncio
async def test_auth_audit_logging(async_client: AsyncClient, audit_superuser_headers: dict):
    """
    Test user registration and login create audit log entries.
    """
    unique_id = uuid.uuid4().hex[:6]
    reg_payload = {
        "full_name": "Audit Test User",
        "email": f"audittest_{unique_id}@example.com",
        "username": f"audittest_{unique_id}",
        "password": "Password123!",
    }
    reg_resp = await async_client.post("/auth/register", json=reg_payload)
    assert reg_resp.status_code == 201

    # Login
    await async_client.post("/auth/login", json={
        "username_or_email": f"audittest_{unique_id}",
        "password": "Password123!",
    })

    # Fetch audit logs as Super Admin
    logs_resp = await async_client.get("/audit/logs", headers=audit_superuser_headers)
    assert logs_resp.status_code == 200
    data = logs_resp.json()["data"]
    actions = [item["action"] for item in data]
    assert "USER_REGISTER" in actions
    assert "LOGIN" in actions


@pytest.mark.asyncio
async def test_audit_logs_security_authorization(
    async_client: AsyncClient, audit_regular_user_headers: dict, audit_superuser_headers: dict
):
    """
    Test security controls for audit endpoints (401 unauthenticated, 403 regular user, 200 superadmin).
    """
    # 1. Unauthenticated request -> 401
    unauth_resp = await async_client.get("/audit/logs")
    assert unauth_resp.status_code == 401

    # 2. Regular user request -> 403
    forbidden_resp = await async_client.get("/audit/logs", headers=audit_regular_user_headers)
    assert forbidden_resp.status_code == 403

    # 3. Super Admin request -> 200
    success_resp = await async_client.get("/audit/logs", headers=audit_superuser_headers)
    assert success_resp.status_code == 200
    assert "data" in success_resp.json()


@pytest.mark.asyncio
async def test_audit_logs_filtering_and_pagination(async_client: AsyncClient, audit_superuser_headers: dict):
    """
    Test filtering audit logs by action, status code, and pagination.
    """
    # Filter by action=LOGIN
    params = {"action": "LOGIN", "page": 1, "page_size": 5}
    response = await async_client.get("/audit/logs", params=params, headers=audit_superuser_headers)
    assert response.status_code == 200
    json_data = response.json()
    assert json_data["page"] == 1
    assert json_data["page_size"] == 5
    for item in json_data["data"]:
        assert item["action"].upper() == "LOGIN"


@pytest.mark.asyncio
async def test_entity_audit_history(async_client: AsyncClient, audit_superuser_headers: dict):
    """
    Test fetching audit history for a specific entity ID.
    """
    unique_id = uuid.uuid4().hex[:6]
    perm_payload = {
        "name": f"Audit Entity Action {unique_id}",
        "code": f"audit.entity_action_{unique_id}",
        "description": "Permission for testing entity audit history",
        "module_name": "audit_module",
    }
    perm_resp = await async_client.post("/permissions", json=perm_payload, headers=audit_superuser_headers)
    assert perm_resp.status_code == 201
    perm_id = perm_resp.json()["id"]

    # Query entity history for Permission
    history_resp = await async_client.get(f"/audit/entity/Permission/{perm_id}", headers=audit_superuser_headers)
    assert history_resp.status_code == 200
    items = history_resp.json()["data"]
    assert len(items) >= 1
    assert items[0]["entity_id"] == str(perm_id)
