"""phase_v060_implement_inventory_foundation

Revision ID: 00f4c360a213
Revises: '00f67d39bb21'
Create Date: 2026-07-29 16:13:20.056180+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00f4c360a213'
down_revision: Union[str, None] = '00f67d39bb21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique brand name'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Brand description or notes'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands'))
    )
    op.create_index(op.f('ix_brands_id'), 'brands', ['id'], unique=False)
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=True)
    op.create_table('product_attributes',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Attribute display name'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique attribute code identifier'),
    sa.Column('data_type', sa.String(length=30), nullable=False, comment='Attribute data type: Text, Number, Boolean, Date, List'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_attributes'))
    )
    op.create_index(op.f('ix_product_attributes_code'), 'product_attributes', ['code'], unique=True)
    op.create_index(op.f('ix_product_attributes_id'), 'product_attributes', ['id'], unique=False)
    op.create_table('product_categories',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique category code identifier (e.g. CAT_ELECTRONICS)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display category name'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Detailed category description'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Foreign key referencing parent ProductCategory for nesting'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], name=op.f('fk_product_categories_parent_id_product_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_categories'))
    )
    op.create_index(op.f('ix_product_categories_code'), 'product_categories', ['code'], unique=True)
    op.create_index(op.f('ix_product_categories_id'), 'product_categories', ['id'], unique=False)
    op.create_index(op.f('ix_product_categories_is_active'), 'product_categories', ['is_active'], unique=False)
    op.create_index(op.f('ix_product_categories_name'), 'product_categories', ['name'], unique=False)
    op.create_index(op.f('ix_product_categories_parent_id'), 'product_categories', ['parent_id'], unique=False)
    op.create_table('unit_of_measures',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Name of measurement unit (e.g. Kilogram)'),
    sa.Column('symbol', sa.String(length=20), nullable=False, comment='Unit symbol abbreviation (e.g. kg, pcs, L)'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Measurement category: Weight, Volume, Length, Count, Time'),
    sa.Column('precision', sa.Integer(), nullable=False, comment='Decimal precision allowed for quantities in this unit'),
    sa.Column('base_unit', sa.String(length=20), nullable=True, comment='Reference symbol of the primary base unit in this category'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_unit_of_measures'))
    )
    op.create_index(op.f('ix_unit_of_measures_category'), 'unit_of_measures', ['category'], unique=False)
    op.create_index(op.f('ix_unit_of_measures_id'), 'unit_of_measures', ['id'], unique=False)
    op.create_index(op.f('ix_unit_of_measures_is_active'), 'unit_of_measures', ['is_active'], unique=False)
    op.create_index(op.f('ix_unit_of_measures_name'), 'unit_of_measures', ['name'], unique=True)
    op.create_index(op.f('ix_unit_of_measures_symbol'), 'unit_of_measures', ['symbol'], unique=True)
    op.create_table('warehouses',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique warehouse code identifier (e.g. WH_MAIN_01)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Warehouse facility name'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='Physical street address'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='Primary warehouse contact manager name'),
    sa.Column('phone', sa.String(length=30), nullable=True, comment='Contact telephone number'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='Contact email address'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_warehouses'))
    )
    op.create_index(op.f('ix_warehouses_code'), 'warehouses', ['code'], unique=True)
    op.create_index(op.f('ix_warehouses_id'), 'warehouses', ['id'], unique=False)
    op.create_index(op.f('ix_warehouses_is_active'), 'warehouses', ['is_active'], unique=False)
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=False)
    op.create_table('storage_locations',
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Foreign key referencing target Warehouse facility'),
    sa.Column('parent_id', sa.UUID(), nullable=True, comment='Foreign key referencing parent StorageLocation for hierarchy'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='Location code identifier within warehouse (e.g. RACK_A_SHELF_2)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Display name of the location'),
    sa.Column('location_type', sa.String(length=50), nullable=False, comment='Location type: Shelf, Rack, Bin, Floor, Cold Storage, Quarantine, Receiving, Dispatch'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['parent_id'], ['storage_locations.id'], name=op.f('fk_storage_locations_parent_id_storage_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_storage_locations_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_locations'))
    )
    op.create_index(op.f('ix_storage_locations_code'), 'storage_locations', ['code'], unique=False)
    op.create_index(op.f('ix_storage_locations_id'), 'storage_locations', ['id'], unique=False)
    op.create_index(op.f('ix_storage_locations_is_active'), 'storage_locations', ['is_active'], unique=False)
    op.create_index(op.f('ix_storage_locations_location_type'), 'storage_locations', ['location_type'], unique=False)
    op.create_index(op.f('ix_storage_locations_parent_id'), 'storage_locations', ['parent_id'], unique=False)
    op.create_index(op.f('ix_storage_locations_warehouse_id'), 'storage_locations', ['warehouse_id'], unique=False)
    op.create_table('products',
    sa.Column('sku', sa.String(length=100), nullable=False, comment='Stock Keeping Unit (globally unique item code)'),
    sa.Column('barcode', sa.String(length=100), nullable=True, comment='Global Trade Item Number / Barcode (unique if provided)'),
    sa.Column('name', sa.String(length=150), nullable=False, comment='Product title / display name'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='Product detailed description'),
    sa.Column('category_id', sa.UUID(), nullable=False, comment='Foreign key referencing product category'),
    sa.Column('brand_id', sa.UUID(), nullable=True, comment='Foreign key referencing brand'),
    sa.Column('base_unit_id', sa.UUID(), nullable=False, comment='Foreign key referencing default base UnitOfMeasure'),
    sa.Column('purchase_unit_id', sa.UUID(), nullable=True, comment='Foreign key referencing purchase UnitOfMeasure'),
    sa.Column('sales_unit_id', sa.UUID(), nullable=True, comment='Foreign key referencing sales UnitOfMeasure'),
    sa.Column('product_type', sa.String(length=50), nullable=False, comment='Product type: Inventory, Service, Consumable, Digital, Asset'),
    sa.Column('track_inventory', sa.Boolean(), nullable=False, comment='Flag indicating if inventory stock levels are tracked'),
    sa.Column('allow_negative_stock', sa.Boolean(), nullable=False, comment='Flag allowing negative stock balances'),
    sa.Column('default_warehouse_id', sa.UUID(), nullable=True, comment='Foreign key referencing default warehouse for stocking'),
    sa.Column('weight', sa.Numeric(precision=10, scale=3), nullable=True, comment='Weight metric'),
    sa.Column('height', sa.Numeric(precision=10, scale=3), nullable=True, comment='Height metric'),
    sa.Column('width', sa.Numeric(precision=10, scale=3), nullable=True, comment='Width metric'),
    sa.Column('length', sa.Numeric(precision=10, scale=3), nullable=True, comment='Length metric'),
    sa.Column('volume', sa.Numeric(precision=10, scale=3), nullable=True, comment='Volume metric'),
    sa.Column('image_file_id', sa.UUID(), nullable=True, comment='Foreign key referencing primary product thumbnail image file'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='Product lifecycle status: Draft, Active, Discontinued, Archived'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['base_unit_id'], ['unit_of_measures.id'], name=op.f('fk_products_base_unit_id_unit_of_measures'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_products_brand_id_brands'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], name=op.f('fk_products_category_id_product_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['default_warehouse_id'], ['warehouses.id'], name=op.f('fk_products_default_warehouse_id_warehouses'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['image_file_id'], ['files.id'], name=op.f('fk_products_image_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['purchase_unit_id'], ['unit_of_measures.id'], name=op.f('fk_products_purchase_unit_id_unit_of_measures'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_unit_id'], ['unit_of_measures.id'], name=op.f('fk_products_sales_unit_id_unit_of_measures'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('ix_products_base_unit_id'), 'products', ['base_unit_id'], unique=False)
    op.create_index(op.f('ix_products_brand_id'), 'products', ['brand_id'], unique=False)
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_product_type'), 'products', ['product_type'], unique=False)
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_table('product_attribute_values',
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Foreign key referencing target Product'),
    sa.Column('attribute_id', sa.UUID(), nullable=False, comment='Foreign key referencing target ProductAttribute definition'),
    sa.Column('value', sa.String(length=500), nullable=False, comment='Assigned attribute value as string representation'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['attribute_id'], ['product_attributes.id'], name=op.f('fk_product_attribute_values_attribute_id_product_attributes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_attribute_values_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_attribute_values')),
    sa.UniqueConstraint('product_id', 'attribute_id', name='uq_product_attribute')
    )
    op.create_index(op.f('ix_product_attribute_values_attribute_id'), 'product_attribute_values', ['attribute_id'], unique=False)
    op.create_index(op.f('ix_product_attribute_values_id'), 'product_attribute_values', ['id'], unique=False)
    op.create_index(op.f('ix_product_attribute_values_product_id'), 'product_attribute_values', ['product_id'], unique=False)
    op.create_table('product_documents',
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Foreign key referencing target Product'),
    sa.Column('file_id', sa.UUID(), nullable=False, comment='Foreign key referencing stored File record'),
    sa.Column('document_type', sa.String(length=50), nullable=False, comment='Document type: Manual, Warranty, Specification, Compliance, Certificate, Image'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_product_documents_file_id_files'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_documents_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_documents'))
    )
    op.create_index(op.f('ix_product_documents_document_type'), 'product_documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_product_documents_file_id'), 'product_documents', ['file_id'], unique=False)
    op.create_index(op.f('ix_product_documents_id'), 'product_documents', ['id'], unique=False)
    op.create_index(op.f('ix_product_documents_product_id'), 'product_documents', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_documents_product_id'), table_name='product_documents')

    op.drop_index(op.f('ix_product_documents_id'), table_name='product_documents')
    op.drop_index(op.f('ix_product_documents_file_id'), table_name='product_documents')
    op.drop_index(op.f('ix_product_documents_document_type'), table_name='product_documents')
    op.drop_table('product_documents')
    op.drop_index(op.f('ix_product_attribute_values_product_id'), table_name='product_attribute_values')
    op.drop_index(op.f('ix_product_attribute_values_id'), table_name='product_attribute_values')
    op.drop_index(op.f('ix_product_attribute_values_attribute_id'), table_name='product_attribute_values')
    op.drop_table('product_attribute_values')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_product_type'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_index(op.f('ix_products_brand_id'), table_name='products')
    op.drop_index(op.f('ix_products_base_unit_id'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_storage_locations_warehouse_id'), table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_parent_id'), table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_location_type'), table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_is_active'), table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_id'), table_name='storage_locations')
    op.drop_index(op.f('ix_storage_locations_code'), table_name='storage_locations')
    op.drop_table('storage_locations')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_is_active'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_id'), table_name='warehouses')
    op.drop_index(op.f('ix_warehouses_code'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_unit_of_measures_symbol'), table_name='unit_of_measures')
    op.drop_index(op.f('ix_unit_of_measures_name'), table_name='unit_of_measures')
    op.drop_index(op.f('ix_unit_of_measures_is_active'), table_name='unit_of_measures')
    op.drop_index(op.f('ix_unit_of_measures_id'), table_name='unit_of_measures')
    op.drop_index(op.f('ix_unit_of_measures_category'), table_name='unit_of_measures')
    op.drop_table('unit_of_measures')
    op.drop_index(op.f('ix_product_categories_parent_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_name'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_is_active'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_id'), table_name='product_categories')
    op.drop_index(op.f('ix_product_categories_code'), table_name='product_categories')
    op.drop_table('product_categories')
    op.drop_index(op.f('ix_product_attributes_id'), table_name='product_attributes')
    op.drop_index(op.f('ix_product_attributes_code'), table_name='product_attributes')
    op.drop_table('product_attributes')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_index(op.f('ix_brands_id'), table_name='brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
