"""phase_v056_implement_payroll_finalization_suite

Revision ID: 00f67d39bb21
Revises: '87b928321932'
Create Date: 2026-07-29 14:12:07.421777+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00f67d39bb21'
down_revision: Union[str, None] = '87b928321932'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_posting_queues',
    sa.Column('payroll_period_id', sa.UUID(), nullable=False),
    sa.Column('posting_status', sa.String(length=50), nullable=False, comment='Pending, Posted, Failed'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Structured financial posting summary payload'),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_financial_posting_queues_payroll_period_id_payroll_periods'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_posting_queues'))
    )
    op.create_index(op.f('ix_financial_posting_queues_id'), 'financial_posting_queues', ['id'], unique=False)
    op.create_index(op.f('ix_financial_posting_queues_payroll_period_id'), 'financial_posting_queues', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_financial_posting_queues_posting_status'), 'financial_posting_queues', ['posting_status'], unique=False)
    op.create_table('payroll_closings',
    sa.Column('payroll_period_id', sa.UUID(), nullable=False),
    sa.Column('closed_by', sa.UUID(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reopened_by', sa.UUID(), nullable=True),
    sa.Column('reopened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closing_remarks', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Open, Closed, Archived'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_payroll_closings_closed_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_payroll_closings_payroll_period_id_payroll_periods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reopened_by'], ['users.id'], name=op.f('fk_payroll_closings_reopened_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_closings'))
    )
    op.create_index(op.f('ix_payroll_closings_id'), 'payroll_closings', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_closings_payroll_period_id'), 'payroll_closings', ['payroll_period_id'], unique=True)
    op.create_index(op.f('ix_payroll_closings_status'), 'payroll_closings', ['status'], unique=False)
    op.create_table('payroll_report_snapshots',
    sa.Column('payroll_period_id', sa.UUID(), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False, comment='Salary Register, Department-wise Payroll, Employee Salary History, Payroll Summary, Deduction Summary, Earnings Summary, Cost Center Report, Monthly Payroll Register'),
    sa.Column('format', sa.String(length=10), nullable=False, comment='PDF, EXCEL, CSV'),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Filter parameters, summary totals, and generation context'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], name=op.f('fk_payroll_report_snapshots_file_id_files'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_payroll_report_snapshots_generated_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_payroll_report_snapshots_payroll_period_id_payroll_periods'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_report_snapshots'))
    )
    op.create_index(op.f('ix_payroll_report_snapshots_id'), 'payroll_report_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_report_snapshots_payroll_period_id'), 'payroll_report_snapshots', ['payroll_period_id'], unique=False)
    op.create_table('payroll_adjustments',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('payroll_period_id', sa.UUID(), nullable=False),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False, comment='Bonus, Incentive, Commission, Overtime, Arrear, Reimbursement, Loan Recovery, Manual Addition, Manual Deduction'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Adjustment numerical amount'),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Pending, Approved, Rejected, Applied'),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_payroll_adjustments_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_adjustments_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_payroll_adjustments_payroll_period_id_payroll_periods'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_adjustments'))
    )
    op.create_index(op.f('ix_payroll_adjustments_employee_id'), 'payroll_adjustments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_id'), 'payroll_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_payroll_period_id'), 'payroll_adjustments', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_payroll_adjustments_status'), 'payroll_adjustments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_adjustments_status'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_payroll_period_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_id'), table_name='payroll_adjustments')
    op.drop_index(op.f('ix_payroll_adjustments_employee_id'), table_name='payroll_adjustments')
    op.drop_table('payroll_adjustments')
    op.drop_index(op.f('ix_payroll_report_snapshots_payroll_period_id'), table_name='payroll_report_snapshots')
    op.drop_index(op.f('ix_payroll_report_snapshots_id'), table_name='payroll_report_snapshots')
    op.drop_table('payroll_report_snapshots')
    op.drop_index(op.f('ix_payroll_closings_status'), table_name='payroll_closings')
    op.drop_index(op.f('ix_payroll_closings_payroll_period_id'), table_name='payroll_closings')
    op.drop_index(op.f('ix_payroll_closings_id'), table_name='payroll_closings')
    op.drop_table('payroll_closings')
    op.drop_index(op.f('ix_financial_posting_queues_posting_status'), table_name='financial_posting_queues')
    op.drop_index(op.f('ix_financial_posting_queues_payroll_period_id'), table_name='financial_posting_queues')
    op.drop_index(op.f('ix_financial_posting_queues_id'), table_name='financial_posting_queues')
    op.drop_table('financial_posting_queues')
    # ### end Alembic commands ###
