"""phase_v050_implement_salary_component

Revision ID: 0c3454e55b21
Revises: 'bffc0a831a09'
Create Date: 2026-07-27 12:23:29.434306+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c3454e55b21'
down_revision: Union[str, None] = 'bffc0a831a09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_components',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique component code identifier (e.g. BASIC, HRA, PF)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique human-readable component name (e.g. Basic Salary, House Rent Allowance)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Detailed component description'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='Component category type: Earning, Deduction'),
    sa.Column('calculation_method', sa.String(length=50), nullable=False, comment='Calculation method: Fixed, Percentage, Formula'),
    sa.Column('default_value', sa.Numeric(precision=12, scale=2), nullable=False, comment='Default fixed amount value'),
    sa.Column('percentage_value', sa.Numeric(precision=5, scale=2), nullable=True, comment='Percentage value (e.g. 50.00 for 50%) when calculation_method is Percentage'),
    sa.Column('is_taxable', sa.Boolean(), nullable=False, comment='True if component is subject to Income Tax calculations'),
    sa.Column('is_pf_applicable', sa.Boolean(), nullable=False, comment='True if component forms part of Provident Fund (PF) calculations'),
    sa.Column('is_esi_applicable', sa.Boolean(), nullable=False, comment='True if component forms part of Employee State Insurance (ESI) calculations'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if component is active for payroll configuration'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Unique sequential ordering number for display and processing'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_components'))
    )
    op.create_index(op.f('ix_salary_components_code'), 'salary_components', ['code'], unique=True)
    op.create_index(op.f('ix_salary_components_display_order'), 'salary_components', ['display_order'], unique=True)
    op.create_index(op.f('ix_salary_components_id'), 'salary_components', ['id'], unique=False)
    op.create_index(op.f('ix_salary_components_is_deleted'), 'salary_components', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_salary_components_name'), 'salary_components', ['name'], unique=True)
    op.create_index(op.f('ix_salary_components_type'), 'salary_components', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_components_type'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_name'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_is_deleted'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_id'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_display_order'), table_name='salary_components')
    op.drop_index(op.f('ix_salary_components_code'), table_name='salary_components')
    op.drop_table('salary_components')
    # ### end Alembic commands ###
