"""phase_hr8_implement_attendance_engine_table

Revision ID: 184caa5625f2
Revises: '9871e1fb35a0'
Create Date: 2026-07-26 16:57:07.819713+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '184caa5625f2'
down_revision: Union[str, None] = '9871e1fb35a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Foreign key referencing employee'),
    sa.Column('attendance_date', sa.Date(), nullable=False, comment='Specific calendar date of attendance record'),
    sa.Column('shift_id', sa.UUID(), nullable=True, comment='Foreign key referencing assigned shift schedule at check-in time'),
    sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when employee checked in (UTC)'),
    sa.Column('check_out_time', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when employee checked out (UTC)'),
    sa.Column('break_minutes', sa.Integer(), nullable=False, comment='Total break time taken during shift in minutes'),
    sa.Column('worked_minutes', sa.Integer(), nullable=False, comment='Total effective working time in minutes'),
    sa.Column('expected_minutes', sa.Integer(), nullable=False, comment='Required standard working time for the shift in minutes'),
    sa.Column('late_minutes', sa.Integer(), nullable=False, comment='Tardiness duration beyond shift grace period in minutes'),
    sa.Column('early_departure_minutes', sa.Integer(), nullable=False, comment='Duration left before shift completion in minutes'),
    sa.Column('attendance_status', sa.String(length=50), nullable=False, comment='Attendance classification status (Present, Late, Half Day, Absent, Holiday, Weekend, On Leave, Missing Check-in, Missing Check-out)'),
    sa.Column('is_manual_correction', sa.Boolean(), nullable=False, comment='True if attendance record was manually corrected by HR/Manager'),
    sa.Column('corrected_by_user_id', sa.UUID(), nullable=True, comment='Foreign key referencing user who performed manual correction'),
    sa.Column('correction_notes', sa.Text(), nullable=True, comment='Audit rationale for manual attendance correction'),
    sa.Column('is_locked', sa.Boolean(), nullable=False, comment='True if attendance is locked for payroll processing'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.ForeignKeyConstraint(['corrected_by_user_id'], ['users.id'], name='fk_attendance_corrected_by_user_id', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_attendance_employee_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='fk_attendance_shift_id', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance')),
    sa.UniqueConstraint('employee_id', 'attendance_date', name='uq_attendance_employee_date')
    )
    op.create_index(op.f('ix_attendance_attendance_date'), 'attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_attendance_status'), 'attendance', ['attendance_status'], unique=False)
    op.create_index('ix_attendance_employee_date', 'attendance', ['employee_id', 'attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_employee_id'), 'attendance', ['employee_id'], unique=False)
    op.create_index(op.f('ix_attendance_id'), 'attendance', ['id'], unique=False)
    op.create_index(op.f('ix_attendance_is_deleted'), 'attendance', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_attendance_is_locked'), 'attendance', ['is_locked'], unique=False)
    op.create_index(op.f('ix_attendance_shift_id'), 'attendance', ['shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_shift_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_is_locked'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_is_deleted'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_id'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_employee_id'), table_name='attendance')
    op.drop_index('ix_attendance_employee_date', table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_status'), table_name='attendance')
    op.drop_index(op.f('ix_attendance_attendance_date'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
