"""phase_hr12_implement_leave_request

Revision ID: 2c2104f01875
Revises: 'bafb9849085f'
Create Date: 2026-07-27 09:53:35.382986+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c2104f01875'
down_revision: Union[str, None] = 'bafb9849085f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_requests',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Foreign Key to Target Employee'),
    sa.Column('leave_type_id', sa.UUID(), nullable=False, comment='Foreign Key to Leave Type Policy'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Leave start date (inclusive)'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='Leave end date (inclusive)'),
    sa.Column('total_days', sa.Float(), nullable=False, comment='Calculated net leave duration (excluding weekends/holidays)'),
    sa.Column('is_half_day', sa.Boolean(), nullable=False, comment='True if leave is for half a day'),
    sa.Column('half_day_session', sa.String(length=50), nullable=True, comment='Half day session (e.g. First Half, Second Half, Morning, Afternoon)'),
    sa.Column('reason', sa.String(length=500), nullable=False, comment='Employee leave application reason'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Workflow status: Draft, Pending, Approved, Rejected, Cancelled, Completed'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when leave request was submitted for approval'),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when leave request was reviewed (approved/rejected)'),
    sa.Column('reviewed_by', sa.UUID(), nullable=True, comment='User ID of reviewer who approved/rejected the request'),
    sa.Column('reviewer_comments', sa.String(length=500), nullable=True, comment='Approval/rejection comments from reviewer'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_requests_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_requests_leave_type_id_leave_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_leave_requests_reviewed_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_requests'))
    )
    op.create_index(op.f('ix_leave_requests_employee_id'), 'leave_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_end_date'), 'leave_requests', ['end_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_id'), 'leave_requests', ['id'], unique=False)
    op.create_index(op.f('ix_leave_requests_is_deleted'), 'leave_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leave_requests_leave_type_id'), 'leave_requests', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_requests_reviewed_by'), 'leave_requests', ['reviewed_by'], unique=False)
    op.create_index(op.f('ix_leave_requests_start_date'), 'leave_requests', ['start_date'], unique=False)
    op.create_index(op.f('ix_leave_requests_status'), 'leave_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_requests_status'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_start_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_reviewed_by'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_leave_type_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_is_deleted'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_id'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_end_date'), table_name='leave_requests')
    op.drop_index(op.f('ix_leave_requests_employee_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    # ### end Alembic commands ###
