"""phase_hr10_implement_leave_type

Revision ID: 49c913ab7229
Revises: 'b05ba39bc33a'
Create Date: 2026-07-27 09:28:44.188999+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49c913ab7229'
down_revision: Union[str, None] = 'b05ba39bc33a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_types',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique leave type code (e.g. ANNUAL, SICK, CASUAL, MATERNITY)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique leave type display name (e.g. Annual Leave, Sick Leave)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of leave policy and entitlement criteria'),
    sa.Column('is_paid', sa.Boolean(), nullable=False, comment='True if leave is paid, False for unpaid leave'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, comment='True if leave application requires manager/HR approval'),
    sa.Column('allow_half_day', sa.Boolean(), nullable=False, comment='True if half-day leave applications are permitted'),
    sa.Column('allow_negative_balance', sa.Boolean(), nullable=False, comment='True if leave balance can go negative (leave deficit)'),
    sa.Column('annual_allocation', sa.Float(), nullable=False, comment='Default annual allocated leave days (>= 0)'),
    sa.Column('carry_forward_allowed', sa.Boolean(), nullable=False, comment='True if unused leave can be carried forward to next year'),
    sa.Column('max_carry_forward', sa.Float(), nullable=False, comment='Maximum number of leave days that can be carried forward'),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=True, comment='Maximum allowed consecutive leave days in a single request'),
    sa.Column('gender_restriction', sa.String(length=20), nullable=True, comment='Optional gender restriction (e.g. Female for Maternity, Male for Paternity)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if leave policy is active and selectable'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_types'))
    )
    op.create_index(op.f('ix_leave_types_code'), 'leave_types', ['code'], unique=True)
    op.create_index(op.f('ix_leave_types_id'), 'leave_types', ['id'], unique=False)
    op.create_index(op.f('ix_leave_types_is_deleted'), 'leave_types', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leave_types_name'), 'leave_types', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_types_name'), table_name='leave_types')
    op.drop_index(op.f('ix_leave_types_is_deleted'), table_name='leave_types')
    op.drop_index(op.f('ix_leave_types_id'), table_name='leave_types')
    op.drop_index(op.f('ix_leave_types_code'), table_name='leave_types')
    op.drop_table('leave_types')
    # ### end Alembic commands ###
