"""Phase 7: Implement Notification and NotificationTemplate tables

Revision ID: 5486a1bd33f4
Revises: 'b1dcd18fe824'
Create Date: 2026-07-26 11:38:44.772585+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5486a1bd33f4'
down_revision: Union[str, None] = 'b1dcd18fe824'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_templates',
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique identifier name of notification template'),
    sa.Column('subject', sa.String(length=255), nullable=True, comment='Email subject line template (supports Jinja2 variables)'),
    sa.Column('template_body', sa.Text(), nullable=False, comment='Jinja2 template body text or HTML content'),
    sa.Column('template_type', sa.String(length=50), server_default='EMAIL', nullable=False, comment='Target channel type (EMAIL, IN_APP)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_templates'))
    )
    op.create_index(op.f('ix_notification_templates_id'), 'notification_templates', ['id'], unique=False)
    op.create_index(op.f('ix_notification_templates_name'), 'notification_templates', ['name'], unique=True)
    op.create_index(op.f('ix_notification_templates_template_type'), 'notification_templates', ['template_type'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False, comment='FK referencing recipient User'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Notification headline title'),
    sa.Column('message', sa.Text(), nullable=False, comment='Full notification message text'),
    sa.Column('notification_type', sa.String(length=50), server_default='IN_APP', nullable=False, comment='Notification channel type (IN_APP, EMAIL, SYSTEM, ALERT)'),
    sa.Column('priority', sa.String(length=20), server_default='MEDIUM', nullable=False, comment='Notification urgency priority level (LOW, MEDIUM, HIGH, URGENT)'),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False, comment='True if notification has been marked as read by user'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when notification was marked as read (UTC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_templates_template_type'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_name'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_id'), table_name='notification_templates')
    op.drop_table('notification_templates')
    # ### end Alembic commands ###
