"""phase_v051_implement_salary_structure

Revision ID: 553f93450df0
Revises: '0c3454e55b21'
Create Date: 2026-07-27 12:43:27.724815+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '553f93450df0'
down_revision: Union[str, None] = '0c3454e55b21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique salary structure code (e.g. EXEC_PAY_V1, ENG_BAND_3)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique human-readable structure name (e.g. Executive Standard Compensation)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Detailed structure description'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='ISO currency code for structure values'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if structure is active for assignment'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Start date when this structure policy becomes effective'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='End date when this structure policy expires (nullable for ongoing structures)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_structures'))
    )
    op.create_index(op.f('ix_salary_structures_code'), 'salary_structures', ['code'], unique=True)
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    op.create_index(op.f('ix_salary_structures_is_deleted'), 'salary_structures', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_salary_structures_name'), 'salary_structures', ['name'], unique=True)
    op.create_table('salary_structure_components',
    sa.Column('salary_structure_id', sa.UUID(), nullable=False, comment='Foreign Key referencing parent SalaryStructure'),
    sa.Column('salary_component_id', sa.UUID(), nullable=False, comment='Foreign Key referencing assigned SalaryComponent'),
    sa.Column('component_order', sa.Integer(), nullable=False, comment='Sequence order position within the structure'),
    sa.Column('component_value', sa.Numeric(precision=12, scale=2), nullable=False, comment='Default amount or baseline value for this component in the structure'),
    sa.Column('calculation_method_override', sa.String(length=50), nullable=True, comment='Optional calculation method override (Fixed, Percentage, Formula)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if component is active in this structure'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['salary_component_id'], ['salary_components.id'], name=op.f('fk_salary_structure_components_salary_component_id_salary_components'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_salary_structure_components_salary_structure_id_salary_structures'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salary_structure_components')),
    sa.UniqueConstraint('salary_structure_id', 'salary_component_id', name='uq_structure_component')
    )
    op.create_index(op.f('ix_salary_structure_components_id'), 'salary_structure_components', ['id'], unique=False)
    op.create_index(op.f('ix_salary_structure_components_salary_component_id'), 'salary_structure_components', ['salary_component_id'], unique=False)
    op.create_index(op.f('ix_salary_structure_components_salary_structure_id'), 'salary_structure_components', ['salary_structure_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_structure_components_salary_structure_id'), table_name='salary_structure_components')
    op.drop_index(op.f('ix_salary_structure_components_salary_component_id'), table_name='salary_structure_components')
    op.drop_index(op.f('ix_salary_structure_components_id'), table_name='salary_structure_components')
    op.drop_table('salary_structure_components')
    op.drop_index(op.f('ix_salary_structures_name'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_is_deleted'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_code'), table_name='salary_structures')
    op.drop_table('salary_structures')
    # ### end Alembic commands ###
