"""Phase 5: Implement AuditLog table

Revision ID: 759f56b581ce
Revises: 'c535ad398047'
Create Date: 2026-07-26 11:25:32.777978+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '759f56b581ce'
down_revision: Union[str, None] = 'c535ad398047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('user_id', sa.UUID(), nullable=True, comment='User ID who performed the action (nullable for unauthenticated/system actions)'),
    sa.Column('username', sa.String(length=100), nullable=True, comment='Username of the performing actor'),
    sa.Column('action', sa.String(length=100), nullable=False, comment='Action performed (e.g. LOGIN, USER_REGISTER, ROLE_ASSIGN, CREATE, UPDATE, DELETE)'),
    sa.Column('entity_type', sa.String(length=100), nullable=False, comment='Target entity type (e.g. User, Role, Permission, Order)'),
    sa.Column('entity_id', sa.String(length=100), nullable=True, comment='Primary Key ID of the target entity'),
    sa.Column('previous_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='State snapshot of entity prior to modification'),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='State snapshot of entity after modification'),
    sa.Column('http_method', sa.String(length=10), nullable=True, comment='HTTP request method (GET, POST, PUT, DELETE)'),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True, comment='API endpoint URL path'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='Unique correlation request ID'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='Client User-Agent header string'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP response status code'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_request_id'), 'audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status_code'), 'audit_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status_code'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_request_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
