"""phase_v054_implement_payroll_runs_and_payslips

Revision ID: 769cb83590b7
Revises: 'ec95e52571cb'
Create Date: 2026-07-29 08:15:39.955413+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '769cb83590b7'
down_revision: Union[str, None] = 'ec95e52571cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_runs',
    sa.Column('payroll_period_id', sa.UUID(), nullable=False, comment='Foreign key to parent PayrollPeriod'),
    sa.Column('run_number', sa.String(length=50), nullable=False, comment='Unique payroll run number (e.g. RUN-202601-001)'),
    sa.Column('run_type', sa.String(length=30), nullable=False, comment='Type of payroll run: Regular, Off Cycle, Adjustment'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='Run status: Draft, Processing, Completed, Locked'),
    sa.Column('started_by', sa.UUID(), nullable=True, comment='User ID who initiated the run execution'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when run was started'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when run finished completion'),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when run was permanently locked'),
    sa.Column('remarks', sa.String(length=255), nullable=True, comment='Optional operational remarks or notes for this run'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_payroll_runs_payroll_period_id_payroll_periods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['started_by'], ['users.id'], name=op.f('fk_payroll_runs_started_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_runs')),
    sa.UniqueConstraint('payroll_period_id', 'run_type', name='uq_period_run_type')
    )
    op.create_index(op.f('ix_payroll_runs_id'), 'payroll_runs', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_payroll_period_id'), 'payroll_runs', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_run_number'), 'payroll_runs', ['run_number'], unique=True)
    op.create_index(op.f('ix_payroll_runs_run_type'), 'payroll_runs', ['run_type'], unique=False)
    op.create_index(op.f('ix_payroll_runs_status'), 'payroll_runs', ['status'], unique=False)
    op.create_table('payslips',
    sa.Column('payroll_record_id', sa.UUID(), nullable=False, comment='Foreign Key referencing source PayrollRecord (1:1 constraint)'),
    sa.Column('payslip_number', sa.String(length=50), nullable=False, comment='Unique payslip document number (e.g. PS-202601-0001)'),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Foreign Key referencing target Employee'),
    sa.Column('payroll_period_id', sa.UUID(), nullable=False, comment='Foreign Key referencing parent PayrollPeriod'),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False, comment='Calculated gross salary amount'),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total earnings sum'),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total deductions sum'),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False, comment='Calculated net salary amount'),
    sa.Column('pdf_file_id', sa.UUID(), nullable=True, comment='Foreign Key referencing generated PDF File artifact'),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when payslip PDF was generated'),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when payslip was published to employee'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='Payslip lifecycle status: Draft, Generated, Published'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payslips_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_payslips_payroll_period_id_payroll_periods'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], name=op.f('fk_payslips_payroll_record_id_payroll_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pdf_file_id'], ['files.id'], name=op.f('fk_payslips_pdf_file_id_files'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payslips'))
    )
    op.create_index(op.f('ix_payslips_employee_id'), 'payslips', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payslips_id'), 'payslips', ['id'], unique=False)
    op.create_index(op.f('ix_payslips_payroll_period_id'), 'payslips', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_payslips_payroll_record_id'), 'payslips', ['payroll_record_id'], unique=True)
    op.create_index(op.f('ix_payslips_payslip_number'), 'payslips', ['payslip_number'], unique=True)
    op.create_index(op.f('ix_payslips_pdf_file_id'), 'payslips', ['pdf_file_id'], unique=False)
    op.create_index(op.f('ix_payslips_status'), 'payslips', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payslips_status'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_pdf_file_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payslip_number'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payroll_record_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_payroll_period_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_id'), table_name='payslips')
    op.drop_index(op.f('ix_payslips_employee_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_payroll_runs_status'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_run_type'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_run_number'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_payroll_period_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    # ### end Alembic commands ###
