"""Phase 2: Add users table

Revision ID: 775a002b20f3
Revises: 'ac3778cfd94c'
Create Date: 2026-07-26 11:03:28.454692+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775a002b20f3'
down_revision: Union[str, None] = 'ac3778cfd94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
