"""phase_v055_implement_statutory_compliance_engine

Revision ID: 87b928321932
Revises: '769cb83590b7'
Create Date: 2026-07-29 11:01:25.450276+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '87b928321932'
down_revision: Union[str, None] = '769cb83590b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('code', sa.String(length=10), nullable=False, comment='ISO country code (e.g. IND, USA, GBR)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Full country name'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Default currency code (e.g. INR, USD, GBP)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_countries'))
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_is_active'), 'countries', ['is_active'], unique=False)
    op.create_table('statutory_rules',
    sa.Column('rule_code', sa.String(length=50), nullable=False, comment='Unique statutory rule code identifier (e.g. IND_PF_STANDARD, IND_PT_MH)'),
    sa.Column('rule_name', sa.String(length=100), nullable=False, comment='Human-readable statutory rule name'),
    sa.Column('country_id', sa.UUID(), nullable=False, comment='Foreign key referencing applicable Country'),
    sa.Column('rule_type', sa.String(length=50), nullable=False, comment='Rule Type: Provident Fund, ESI, Professional Tax, Income Tax, Other'),
    sa.Column('calculation_method', sa.String(length=50), nullable=False, comment='Calculation Method: Fixed, Percentage, Slab'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Effective start date of rule policy'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Optional effective end date of rule policy'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Evaluation priority order (1 is highest priority)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed statutory rule description'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_statutory_rules_country_id_countries'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statutory_rules'))
    )
    op.create_index(op.f('ix_statutory_rules_country_id'), 'statutory_rules', ['country_id'], unique=False)
    op.create_index(op.f('ix_statutory_rules_id'), 'statutory_rules', ['id'], unique=False)
    op.create_index(op.f('ix_statutory_rules_is_active'), 'statutory_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_statutory_rules_is_deleted'), 'statutory_rules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_statutory_rules_rule_code'), 'statutory_rules', ['rule_code'], unique=True)
    op.create_index(op.f('ix_statutory_rules_rule_type'), 'statutory_rules', ['rule_type'], unique=False)
    op.create_table('statutory_rule_slabs',
    sa.Column('statutory_rule_id', sa.UUID(), nullable=False, comment='Foreign key referencing parent StatutoryRule'),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Lower salary boundary for slab (inclusive)'),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=2), nullable=True, comment='Upper salary boundary for slab (inclusive, null means infinity)'),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False, comment='Percentage rate applied in slab'),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Fixed deduction amount applied in slab'),
    sa.Column('sequence', sa.Integer(), nullable=False, comment='Sequence index ordering slabs within rule'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['statutory_rule_id'], ['statutory_rules.id'], name=op.f('fk_statutory_rule_slabs_statutory_rule_id_statutory_rules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statutory_rule_slabs'))
    )
    op.create_index(op.f('ix_statutory_rule_slabs_id'), 'statutory_rule_slabs', ['id'], unique=False)
    op.create_index(op.f('ix_statutory_rule_slabs_statutory_rule_id'), 'statutory_rule_slabs', ['statutory_rule_id'], unique=False)
    op.create_table('employee_statutory_profiles',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Foreign key referencing Employee'),
    sa.Column('country_id', sa.UUID(), nullable=False, comment='Foreign key referencing Country jurisdiction'),
    sa.Column('pf_enabled', sa.Boolean(), nullable=False, comment='Flag indicating if Provident Fund deduction is enabled'),
    sa.Column('esi_enabled', sa.Boolean(), nullable=False, comment='Flag indicating if ESI deduction is enabled'),
    sa.Column('professional_tax_enabled', sa.Boolean(), nullable=False, comment='Flag indicating if Professional Tax deduction is enabled'),
    sa.Column('income_tax_enabled', sa.Boolean(), nullable=False, comment='Flag indicating if Income Tax deduction is enabled'),
    sa.Column('tax_identification_number', sa.String(length=50), nullable=True, comment='Tax ID / Permanent Account Number (PAN / SSN)'),
    sa.Column('pf_number', sa.String(length=50), nullable=True, comment='Provident Fund Account / UAN Number'),
    sa.Column('esi_number', sa.String(length=50), nullable=True, comment='ESI Insurance Number'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Effective start date of statutory profile'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='Optional effective end date of statutory profile'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_employee_statutory_profiles_country_id_countries'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_statutory_profiles_employee_id_employees'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_statutory_profiles'))
    )
    op.create_index(op.f('ix_employee_statutory_profiles_country_id'), 'employee_statutory_profiles', ['country_id'], unique=False)
    op.create_index(op.f('ix_employee_statutory_profiles_employee_id'), 'employee_statutory_profiles', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_statutory_profiles_id'), 'employee_statutory_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_employee_statutory_profiles_is_active'), 'employee_statutory_profiles', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_statutory_profiles_is_active'), table_name='employee_statutory_profiles')
    op.drop_index(op.f('ix_employee_statutory_profiles_id'), table_name='employee_statutory_profiles')
    op.drop_index(op.f('ix_employee_statutory_profiles_employee_id'), table_name='employee_statutory_profiles')
    op.drop_index(op.f('ix_employee_statutory_profiles_country_id'), table_name='employee_statutory_profiles')
    op.drop_table('employee_statutory_profiles')
    op.drop_index(op.f('ix_statutory_rule_slabs_statutory_rule_id'), table_name='statutory_rule_slabs')
    op.drop_index(op.f('ix_statutory_rule_slabs_id'), table_name='statutory_rule_slabs')
    op.drop_table('statutory_rule_slabs')
    op.drop_index(op.f('ix_statutory_rules_rule_type'), table_name='statutory_rules')
    op.drop_index(op.f('ix_statutory_rules_rule_code'), table_name='statutory_rules')
    op.drop_index(op.f('ix_statutory_rules_is_deleted'), table_name='statutory_rules')
    op.drop_index(op.f('ix_statutory_rules_is_active'), table_name='statutory_rules')
    op.drop_index(op.f('ix_statutory_rules_id'), table_name='statutory_rules')
    op.drop_index(op.f('ix_statutory_rules_country_id'), table_name='statutory_rules')
    op.drop_table('statutory_rules')
    op.drop_index(op.f('ix_countries_is_active'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
