"""phase_hr7_implement_holiday_calendar_table

Revision ID: 9871e1fb35a0
Revises: '9eb88bfb9c06'
Create Date: 2026-07-26 16:43:45.984985+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9871e1fb35a0'
down_revision: Union[str, None] = '9eb88bfb9c06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique holiday code (e.g. HOL-2026-IND-DAY)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Official holiday name (e.g. Independence Day)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed holiday description'),
    sa.Column('holiday_date', sa.Date(), nullable=False, comment='Specific date of the holiday'),
    sa.Column('holiday_type', sa.String(length=50), nullable=False, comment='Holiday classification (National, Regional, Company, Optional)'),
    sa.Column('country', sa.String(length=100), nullable=False, comment='Target country for national/regional holidays'),
    sa.Column('state_region', sa.String(length=100), nullable=True, comment='Target state or province for regional holidays'),
    sa.Column('is_half_day', sa.Boolean(), nullable=False, comment='True if holiday is observed for a half day'),
    sa.Column('is_recurring_annually', sa.Boolean(), nullable=False, comment='True if holiday automatically recurs on the same month/day every year'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active holiday status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_holidays'))
    )
    op.create_index(op.f('ix_holidays_code'), 'holidays', ['code'], unique=True)
    op.create_index(op.f('ix_holidays_holiday_date'), 'holidays', ['holiday_date'], unique=False)
    op.create_index(op.f('ix_holidays_id'), 'holidays', ['id'], unique=False)
    op.create_index(op.f('ix_holidays_is_active'), 'holidays', ['is_active'], unique=False)
    op.create_index(op.f('ix_holidays_is_deleted'), 'holidays', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_holidays_name'), 'holidays', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holidays_name'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_is_deleted'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_is_active'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_id'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_holiday_date'), table_name='holidays')
    op.drop_index(op.f('ix_holidays_code'), table_name='holidays')
    op.drop_table('holidays')
    # ### end Alembic commands ###
