"""phase_hr6_implement_shifts_table_and_employee_shift_id

Revision ID: 9eb88bfb9c06
Revises: 'f3515986f924'
Create Date: 2026-07-26 16:34:34.557079+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eb88bfb9c06'
down_revision: Union[str, None] = 'f3515986f924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique shift identifier code (e.g. SHIFT-DAY-01)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Unique shift name (e.g. Morning Shift, Night Shift)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed shift schedule description'),
    sa.Column('start_time', sa.Time(), nullable=False, comment='Shift start time (e.g. 09:00:00)'),
    sa.Column('end_time', sa.Time(), nullable=False, comment='Shift end time (e.g. 17:00:00 or 06:00:00 for overnight)'),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=False, comment='Total allocated break duration in minutes'),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False, comment='Allowed late arrival grace period in minutes'),
    sa.Column('minimum_working_hours', sa.Float(), nullable=False, comment='Minimum required hours for half-day credit'),
    sa.Column('maximum_working_hours', sa.Float(), nullable=False, comment='Maximum allowed daily working hours including overtime'),
    sa.Column('is_night_shift', sa.Boolean(), nullable=False, comment='True if shift spans overnight across midnight'),
    sa.Column('is_flexible_shift', sa.Boolean(), nullable=False, comment='True if shift supports flexible start/end hours'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active shift status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shifts'))
    )
    op.create_index(op.f('ix_shifts_code'), 'shifts', ['code'], unique=True)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_index(op.f('ix_shifts_is_active'), 'shifts', ['is_active'], unique=False)
    op.create_index(op.f('ix_shifts_is_deleted'), 'shifts', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shifts_name'), 'shifts', ['name'], unique=True)
    op.add_column('employees', sa.Column('shift_id', sa.UUID(), nullable=True, comment='FK referencing assigned Shift schedule'))
    op.create_index(op.f('ix_employees_shift_id'), 'employees', ['shift_id'], unique=False)
    op.create_foreign_key(op.f('fk_employees_shift_id_shifts'), 'employees', 'shifts', ['shift_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_employees_shift_id_shifts'), 'employees', type_='foreignkey')
    op.drop_index(op.f('ix_employees_shift_id'), table_name='employees')
    op.drop_column('employees', 'shift_id')
    op.drop_index(op.f('ix_shifts_name'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_is_deleted'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_is_active'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_code'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
