"""phase_v052_implement_employee_compensation

Revision ID: a3cad77f4bbb
Revises: '553f93450df0'
Create Date: 2026-07-27 13:07:33.717515+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cad77f4bbb'
down_revision: Union[str, None] = '553f93450df0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_compensations',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Foreign Key referencing assigned Employee'),
    sa.Column('salary_structure_id', sa.UUID(), nullable=False, comment='Foreign Key referencing assigned SalaryStructure template'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Start date when this compensation policy takes effect'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='End date when this compensation policy expires (nullable if ongoing)'),
    sa.Column('annual_ctc', sa.Numeric(precision=12, scale=2), nullable=False, comment='Total Cost to Company (CTC) per annum'),
    sa.Column('monthly_gross_salary', sa.Numeric(precision=12, scale=2), nullable=False, comment='Monthly gross salary amount before statutory deductions'),
    sa.Column('monthly_net_salary', sa.Numeric(precision=12, scale=2), nullable=True, comment='Estimated monthly net salary amount (reserved for future calculation)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Compensation status: Draft, Active, Expired, Cancelled'),
    sa.Column('revision_number', sa.Integer(), nullable=False, comment='Sequential revision number (increments with salary revisions)'),
    sa.Column('previous_compensation_id', sa.UUID(), nullable=True, comment='Foreign Key referencing previous compensation version if revised'),
    sa.Column('remarks', sa.String(length=255), nullable=True, comment='Remarks or justification for compensation assignment/revision'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='User ID of authorized HR/Payroll Manager who activated this compensation'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when compensation was activated and approved'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_employee_compensations_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_employee_compensations_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['previous_compensation_id'], ['employee_compensations.id'], name=op.f('fk_employee_compensations_previous_compensation_id_employee_compensations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['salary_structure_id'], ['salary_structures.id'], name=op.f('fk_employee_compensations_salary_structure_id_salary_structures'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_employee_compensations'))
    )
    op.create_index(op.f('ix_employee_compensations_effective_from'), 'employee_compensations', ['effective_from'], unique=False)
    op.create_index(op.f('ix_employee_compensations_employee_id'), 'employee_compensations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_compensations_id'), 'employee_compensations', ['id'], unique=False)
    op.create_index(op.f('ix_employee_compensations_is_deleted'), 'employee_compensations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_employee_compensations_previous_compensation_id'), 'employee_compensations', ['previous_compensation_id'], unique=False)
    op.create_index(op.f('ix_employee_compensations_salary_structure_id'), 'employee_compensations', ['salary_structure_id'], unique=False)
    op.create_index(op.f('ix_employee_compensations_status'), 'employee_compensations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_compensations_status'), table_name='employee_compensations')
    op.drop_index(op.f('ix_employee_compensations_salary_structure_id'), table_name='employee_compensations')
    op.drop_index(op.f('ix_employee_compensations_previous_compensation_id'), table_name='employee_compensations')
    op.drop_index(op.f('ix_employee_compensations_is_deleted'), table_name='employee_compensations')
    op.drop_index(op.f('ix_employee_compensations_id'), table_name='employee_compensations')
    op.drop_index(op.f('ix_employee_compensations_employee_id'), table_name='employee_compensations')
    op.drop_index(op.f('ix_employee_compensations_effective_from'), table_name='employee_compensations')
    op.drop_table('employee_compensations')
    # ### end Alembic commands ###
