"""phase_hr9_implement_shift_assignment

Revision ID: b05ba39bc33a
Revises: '184caa5625f2'
Create Date: 2026-07-27 08:56:53.637061+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b05ba39bc33a'
down_revision: Union[str, None] = '184caa5625f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_assignments',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Foreign key referencing target Employee'),
    sa.Column('shift_id', sa.UUID(), nullable=False, comment='Foreign key referencing assigned Shift'),
    sa.Column('effective_from', sa.Date(), nullable=False, comment='Start date from which this shift assignment is effective'),
    sa.Column('effective_to', sa.Date(), nullable=True, comment='End date until which this shift assignment is effective (NULL for open-ended)'),
    sa.Column('assignment_type', sa.String(length=50), nullable=False, comment='Assignment schedule type: Permanent, Temporary, or Rotation'),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason or operational justification for assignment'),
    sa.Column('assigned_by', sa.UUID(), nullable=True, comment='User ID of admin or manager who created/authorized this assignment'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating if assignment is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name='fk_shift_assignment_assigned_by', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_shift_assignment_employee_id', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], name='fk_shift_assignment_shift_id', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shift_assignments'))
    )
    op.create_index('idx_shift_assign_emp_dates', 'shift_assignments', ['employee_id', 'effective_from', 'effective_to'], unique=False)
    op.create_index(op.f('ix_shift_assignments_effective_from'), 'shift_assignments', ['effective_from'], unique=False)
    op.create_index(op.f('ix_shift_assignments_effective_to'), 'shift_assignments', ['effective_to'], unique=False)
    op.create_index(op.f('ix_shift_assignments_employee_id'), 'shift_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_id'), 'shift_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_shift_assignments_is_active'), 'shift_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_shift_assignments_is_deleted'), 'shift_assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_shift_assignments_shift_id'), 'shift_assignments', ['shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('idx_shift_assign_emp_dates', table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_shift_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_is_deleted'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_is_active'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_employee_id'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_effective_to'), table_name='shift_assignments')
    op.drop_index(op.f('ix_shift_assignments_effective_from'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    # ### end Alembic commands ###
