"""Phase 6: Implement File table

Revision ID: b1dcd18fe824
Revises: '759f56b581ce'
Create Date: 2026-07-26 11:30:23.031074+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1dcd18fe824'
down_revision: Union[str, None] = '759f56b581ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original client filename'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='Unique generated stored filename'),
    sa.Column('file_extension', sa.String(length=20), nullable=False, comment='File extension without leading dot (e.g. pdf, png)'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='MIME content type string'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='File size in bytes'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='Relative path to stored asset (internal use only)'),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False, comment='FK referencing User who uploaded the file'),
    sa.Column('entity_type', sa.String(length=100), nullable=True, comment='Target ERP entity type attached to (e.g. Employee, Invoice)'),
    sa.Column('entity_id', sa.String(length=100), nullable=True, comment='Primary Key ID of target attached entity'),
    sa.Column('checksum', sa.String(length=64), nullable=False, comment='SHA256 hex digest checksum for duplicate detection'),
    sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False, comment='True if publicly accessible without authentication'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_files_uploaded_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_files'))
    )
    op.create_index(op.f('ix_files_checksum'), 'files', ['checksum'], unique=False)
    op.create_index(op.f('ix_files_entity_id'), 'files', ['entity_id'], unique=False)
    op.create_index(op.f('ix_files_entity_type'), 'files', ['entity_type'], unique=False)
    op.create_index(op.f('ix_files_id'), 'files', ['id'], unique=False)
    op.create_index(op.f('ix_files_uploaded_by_id'), 'files', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_files_uploaded_by_id'), table_name='files')
    op.drop_index(op.f('ix_files_id'), table_name='files')
    op.drop_index(op.f('ix_files_entity_type'), table_name='files')
    op.drop_index(op.f('ix_files_entity_id'), table_name='files')
    op.drop_index(op.f('ix_files_checksum'), table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
