"""phase_v062_implement_warehouse_operations_engine

Revision ID: b8b2e8a866c5
Revises: 'c8a97096a1e6'
Create Date: 2026-07-31 10:47:36.135344+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8b2e8a866c5'
down_revision: Union[str, None] = 'c8a97096a1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goods_issues',
    sa.Column('issue_number', sa.String(length=100), nullable=False, comment='Unique goods issue document number'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Source warehouse facility'),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False, comment='Effective date and time of physical issue (UTC)'),
    sa.Column('issue_reason', sa.String(length=50), nullable=False, comment='Issue reason: Consumption, Internal, Damage, Sample, Adjustment, Other'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Document status: Draft, Issued, Cancelled'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Remarks or issue justification notes'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User ID who created the issue document'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='User ID who approved or executed the issue document'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when document was approved/issued (UTC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_goods_issues_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_goods_issues_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_goods_issues_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_issues'))
    )
    op.create_index(op.f('ix_goods_issues_id'), 'goods_issues', ['id'], unique=False)
    op.create_index(op.f('ix_goods_issues_issue_number'), 'goods_issues', ['issue_number'], unique=True)
    op.create_index(op.f('ix_goods_issues_status'), 'goods_issues', ['status'], unique=False)
    op.create_index(op.f('ix_goods_issues_warehouse_id'), 'goods_issues', ['warehouse_id'], unique=False)
    op.create_table('goods_receipts',
    sa.Column('receipt_number', sa.String(length=100), nullable=False, comment='Unique goods receipt document number'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Destination warehouse facility'),
    sa.Column('supplier_reference', sa.String(length=100), nullable=True, comment='Optional supplier invoice or challan reference number'),
    sa.Column('external_reference', sa.String(length=100), nullable=True, comment='Optional external document reference (e.g., PO number)'),
    sa.Column('receipt_date', sa.DateTime(timezone=True), nullable=False, comment='Effective date and time of physical receipt (UTC)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Document status: Draft, Received, Cancelled'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Remarks or receiving notes'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User ID who created the receipt document'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='User ID who approved or received the document'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when document was approved/received (UTC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_goods_receipts_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_goods_receipts_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_goods_receipts_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipts'))
    )
    op.create_index(op.f('ix_goods_receipts_id'), 'goods_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_goods_receipts_receipt_number'), 'goods_receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_goods_receipts_status'), 'goods_receipts', ['status'], unique=False)
    op.create_index(op.f('ix_goods_receipts_warehouse_id'), 'goods_receipts', ['warehouse_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('transfer_number', sa.String(length=100), nullable=False, comment='Unique stock transfer document number'),
    sa.Column('source_warehouse_id', sa.UUID(), nullable=False, comment='Source warehouse facility'),
    sa.Column('destination_warehouse_id', sa.UUID(), nullable=False, comment='Destination warehouse facility'),
    sa.Column('source_location_id', sa.UUID(), nullable=True, comment='Optional source storage location within source warehouse'),
    sa.Column('destination_location_id', sa.UUID(), nullable=True, comment='Optional destination storage location within destination warehouse'),
    sa.Column('transfer_date', sa.DateTime(timezone=True), nullable=False, comment='Effective date and time of transfer initiation (UTC)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Document status: Draft, In Transit, Completed, Cancelled'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Remarks or transfer notes'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User ID who created the transfer proposal'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='User ID who approved or dispatched the transfer'),
    sa.Column('completed_by', sa.UUID(), nullable=True, comment='User ID who completed/received the transfer at destination'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_stock_transfers_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], name=op.f('fk_stock_transfers_completed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_transfers_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_location_id'], ['storage_locations.id'], name=op.f('fk_stock_transfers_destination_location_id_storage_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['destination_warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_transfers_destination_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_location_id'], ['storage_locations.id'], name=op.f('fk_stock_transfers_source_location_id_storage_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_transfers_source_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfers'))
    )
    op.create_index(op.f('ix_stock_transfers_destination_location_id'), 'stock_transfers', ['destination_location_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_destination_warehouse_id'), 'stock_transfers', ['destination_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_id'), 'stock_transfers', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_source_location_id'), 'stock_transfers', ['source_location_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_source_warehouse_id'), 'stock_transfers', ['source_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_status'), 'stock_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_stock_transfers_transfer_number'), 'stock_transfers', ['transfer_number'], unique=True)
    op.create_table('goods_issue_items',
    sa.Column('goods_issue_id', sa.UUID(), nullable=False, comment='Parent GoodsIssue document reference'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Reference to Product master record'),
    sa.Column('storage_location_id', sa.UUID(), nullable=True, comment='Source storage location within warehouse'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Issued stock quantity'),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='Unit of Measure for issued quantity'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Line item remarks'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.ForeignKeyConstraint(['goods_issue_id'], ['goods_issues.id'], name=op.f('fk_goods_issue_items_goods_issue_id_goods_issues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_goods_issue_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], name=op.f('fk_goods_issue_items_storage_location_id_storage_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_of_measures.id'], name=op.f('fk_goods_issue_items_unit_id_unit_of_measures'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_issue_items'))
    )
    op.create_index(op.f('ix_goods_issue_items_goods_issue_id'), 'goods_issue_items', ['goods_issue_id'], unique=False)
    op.create_index(op.f('ix_goods_issue_items_id'), 'goods_issue_items', ['id'], unique=False)
    op.create_index(op.f('ix_goods_issue_items_product_id'), 'goods_issue_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_goods_issue_items_storage_location_id'), 'goods_issue_items', ['storage_location_id'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False, comment='Parent GoodsReceipt document reference'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Reference to Product master record'),
    sa.Column('storage_location_id', sa.UUID(), nullable=True, comment='Destination storage location within warehouse'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Received quantity'),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='Unit of Measure for received quantity'),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=True, comment='Unit cost of received goods'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Line item remarks or condition notes'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipts.id'], name=op.f('fk_goods_receipt_items_goods_receipt_id_goods_receipts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_goods_receipt_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], name=op.f('fk_goods_receipt_items_storage_location_id_storage_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_of_measures.id'], name=op.f('fk_goods_receipt_items_unit_id_unit_of_measures'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_goods_receipt_items'))
    )
    op.create_index(op.f('ix_goods_receipt_items_goods_receipt_id'), 'goods_receipt_items', ['goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_id'), 'goods_receipt_items', ['id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_product_id'), 'goods_receipt_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_storage_location_id'), 'goods_receipt_items', ['storage_location_id'], unique=False)
    op.create_table('stock_transfer_items',
    sa.Column('transfer_id', sa.UUID(), nullable=False, comment='Parent StockTransfer document reference'),
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Reference to Product master record'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Transferred stock quantity'),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='Unit of Measure for transferred quantity'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Line item remarks'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_transfer_items_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['transfer_id'], ['stock_transfers.id'], name=op.f('fk_stock_transfer_items_transfer_id_stock_transfers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_of_measures.id'], name=op.f('fk_stock_transfer_items_unit_id_unit_of_measures'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_transfer_items'))
    )
    op.create_index(op.f('ix_stock_transfer_items_id'), 'stock_transfer_items', ['id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_product_id'), 'stock_transfer_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transfer_items_transfer_id'), 'stock_transfer_items', ['transfer_id'], unique=False)
    op.drop_index('ix_dummy_products_id', table_name='dummy_products')
    op.drop_index('ix_dummy_products_is_deleted', table_name='dummy_products')
    op.drop_table('dummy_products')
    op.create_index(op.f('ix_stock_ledgers_warehouse_id'), 'stock_ledgers', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ledgers_warehouse_id'), table_name='stock_ledgers')
    op.create_table('dummy_products',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name='pk_dummy_products'),
    sa.UniqueConstraint('code', name='uq_dummy_products_code', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_dummy_products_is_deleted', 'dummy_products', ['is_deleted'], unique=False)
    op.create_index('ix_dummy_products_id', 'dummy_products', ['id'], unique=False)
    op.drop_index(op.f('ix_stock_transfer_items_transfer_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_items_product_id'), table_name='stock_transfer_items')
    op.drop_index(op.f('ix_stock_transfer_items_id'), table_name='stock_transfer_items')
    op.drop_table('stock_transfer_items')
    op.drop_index(op.f('ix_goods_receipt_items_storage_location_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_product_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_goods_receipt_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index(op.f('ix_goods_issue_items_storage_location_id'), table_name='goods_issue_items')
    op.drop_index(op.f('ix_goods_issue_items_product_id'), table_name='goods_issue_items')
    op.drop_index(op.f('ix_goods_issue_items_id'), table_name='goods_issue_items')
    op.drop_index(op.f('ix_goods_issue_items_goods_issue_id'), table_name='goods_issue_items')
    op.drop_table('goods_issue_items')
    op.drop_index(op.f('ix_stock_transfers_transfer_number'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_status'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_source_warehouse_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_source_location_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_destination_warehouse_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_destination_location_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_goods_receipts_warehouse_id'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_status'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_receipt_number'), table_name='goods_receipts')
    op.drop_index(op.f('ix_goods_receipts_id'), table_name='goods_receipts')
    op.drop_table('goods_receipts')
    op.drop_index(op.f('ix_goods_issues_warehouse_id'), table_name='goods_issues')
    op.drop_index(op.f('ix_goods_issues_status'), table_name='goods_issues')
    op.drop_index(op.f('ix_goods_issues_issue_number'), table_name='goods_issues')
    op.drop_index(op.f('ix_goods_issues_id'), table_name='goods_issues')
    op.drop_table('goods_issues')
    # ### end Alembic commands ###
