"""phase_hr11_implement_leave_balance

Revision ID: bafb9849085f
Revises: '49c913ab7229'
Create Date: 2026-07-27 09:38:59.370036+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bafb9849085f'
down_revision: Union[str, None] = '49c913ab7229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leave_balances',
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Foreign Key to Target Employee'),
    sa.Column('leave_type_id', sa.UUID(), nullable=False, comment='Foreign Key to Leave Type Policy'),
    sa.Column('leave_year', sa.Integer(), nullable=False, comment='Calendar leave year (e.g. 2026)'),
    sa.Column('opening_balance', sa.Float(), nullable=False, comment='Opening leave balance at start of leave year'),
    sa.Column('allocated_days', sa.Float(), nullable=False, comment='Annual allocated leave days'),
    sa.Column('earned_days', sa.Float(), nullable=False, comment='Accrued/earned leave days during the year'),
    sa.Column('availed_days', sa.Float(), nullable=False, comment='Leave days used/taken by employee'),
    sa.Column('encashed_days', sa.Float(), nullable=False, comment='Leave days cashed out/encashed by employee'),
    sa.Column('carried_forward_days', sa.Float(), nullable=False, comment='Unused leave carried forward from previous year'),
    sa.Column('remaining_days', sa.Float(), nullable=False, comment='Current available remaining leave balance (derived)'),
    sa.Column('last_updated_by', sa.UUID(), nullable=True, comment='User ID who performed last manual adjustment'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if leave balance is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_leave_balances_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], name=op.f('fk_leave_balances_last_updated_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['leave_type_id'], ['leave_types.id'], name=op.f('fk_leave_balances_leave_type_id_leave_types'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_leave_balances')),
    sa.UniqueConstraint('employee_id', 'leave_type_id', 'leave_year', name='uq_employee_leave_type_year')
    )
    op.create_index(op.f('ix_leave_balances_employee_id'), 'leave_balances', ['employee_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_id'), 'leave_balances', ['id'], unique=False)
    op.create_index(op.f('ix_leave_balances_is_deleted'), 'leave_balances', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_leave_balances_leave_type_id'), 'leave_balances', ['leave_type_id'], unique=False)
    op.create_index(op.f('ix_leave_balances_leave_year'), 'leave_balances', ['leave_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leave_balances_leave_year'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_leave_type_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_is_deleted'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_id'), table_name='leave_balances')
    op.drop_index(op.f('ix_leave_balances_employee_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    # ### end Alembic commands ###
