"""phase_v045_implement_approval_engine

Revision ID: bffc0a831a09
Revises: '2c2104f01875'
Create Date: 2026-07-27 10:35:44.141509+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bffc0a831a09'
down_revision: Union[str, None] = '2c2104f01875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_workflows',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique workflow code identifier (e.g. WF_LEAVE_DEFAULT)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable workflow name (e.g. Standard Leave Approval Workflow)'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='Detailed workflow description'),
    sa.Column('module_name', sa.String(length=50), nullable=False, comment='Associated module name (e.g. leave, expense, purchase_order, platform)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if workflow definition is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_workflows'))
    )
    op.create_index(op.f('ix_approval_workflows_code'), 'approval_workflows', ['code'], unique=True)
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflows_is_deleted'), 'approval_workflows', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_approval_workflows_module_name'), 'approval_workflows', ['module_name'], unique=False)
    op.create_index(op.f('ix_approval_workflows_name'), 'approval_workflows', ['name'], unique=False)
    op.create_table('approval_requests',
    sa.Column('workflow_id', sa.UUID(), nullable=False, comment='FK to ApprovalWorkflow definition'),
    sa.Column('entity_type', sa.String(length=100), nullable=False, comment='Target domain entity type (e.g. LeaveRequest, ExpenseClaim, PurchaseOrder)'),
    sa.Column('entity_id', sa.String(length=100), nullable=False, comment='Target domain entity ID/UUID'),
    sa.Column('current_step_number', sa.Integer(), nullable=False, comment='Current pending step number in approval sequence'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Approval status: Draft, Pending, Approved, Rejected, Cancelled'),
    sa.Column('submitted_by', sa.UUID(), nullable=False, comment='FK to User who submitted the request'),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False, comment='Submission timestamp (UTC)'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='Completion timestamp (UTC) when approved/rejected/cancelled'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name=op.f('fk_approval_requests_submitted_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], name=op.f('fk_approval_requests_workflow_id_approval_workflows'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index(op.f('ix_approval_requests_entity_id'), 'approval_requests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_entity_type'), 'approval_requests', ['entity_type'], unique=False)
    op.create_index(op.f('ix_approval_requests_id'), 'approval_requests', ['id'], unique=False)
    op.create_index(op.f('ix_approval_requests_is_deleted'), 'approval_requests', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_submitted_by'), 'approval_requests', ['submitted_by'], unique=False)
    op.create_index(op.f('ix_approval_requests_workflow_id'), 'approval_requests', ['workflow_id'], unique=False)
    op.create_table('approval_steps',
    sa.Column('workflow_id', sa.UUID(), nullable=False, comment='FK to parent ApprovalWorkflow'),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='Sequential step number (1, 2, 3...)'),
    sa.Column('approver_role_id', sa.UUID(), nullable=False, comment='FK to Role authorized to approve this step'),
    sa.Column('required_approvals', sa.Integer(), nullable=False, comment='Number of required approvals at this step'),
    sa.Column('auto_approve', sa.Boolean(), nullable=False, comment='True if step is auto-approved under business conditions'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if step is active'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.ForeignKeyConstraint(['approver_role_id'], ['roles.id'], name=op.f('fk_approval_steps_approver_role_id_roles'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workflow_id'], ['approval_workflows.id'], name=op.f('fk_approval_steps_workflow_id_approval_workflows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_steps')),
    sa.UniqueConstraint('workflow_id', 'step_number', name='uq_workflow_step_number')
    )
    op.create_index(op.f('ix_approval_steps_approver_role_id'), 'approval_steps', ['approver_role_id'], unique=False)
    op.create_index(op.f('ix_approval_steps_id'), 'approval_steps', ['id'], unique=False)
    op.create_index(op.f('ix_approval_steps_is_deleted'), 'approval_steps', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_approval_steps_workflow_id'), 'approval_steps', ['workflow_id'], unique=False)
    op.create_table('approval_histories',
    sa.Column('approval_request_id', sa.UUID(), nullable=False, comment='FK to parent ApprovalRequest'),
    sa.Column('step_number', sa.Integer(), nullable=False, comment='Step number at which action was taken'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='Action performed: Submitting, Approved Step, Rejected, Cancelled, Completed Workflow'),
    sa.Column('comments', sa.String(length=500), nullable=True, comment='Comments/justification provided by action performer'),
    sa.Column('performed_by', sa.UUID(), nullable=False, comment='FK to User who performed the action'),
    sa.Column('action_time', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when action was performed (UTC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_approval_histories_approval_request_id_approval_requests'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_approval_histories_performed_by_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_histories'))
    )
    op.create_index(op.f('ix_approval_histories_approval_request_id'), 'approval_histories', ['approval_request_id'], unique=False)
    op.create_index(op.f('ix_approval_histories_id'), 'approval_histories', ['id'], unique=False)
    op.create_index(op.f('ix_approval_histories_performed_by'), 'approval_histories', ['performed_by'], unique=False)
    op.drop_index('ix_test_products_id', table_name='test_products')
    op.drop_index('ix_test_products_is_deleted', table_name='test_products')
    op.drop_table('test_products')
    op.drop_index('ix_dummy_products_id', table_name='dummy_products')
    op.drop_index('ix_dummy_products_is_deleted', table_name='dummy_products')
    op.drop_table('dummy_products')
    op.alter_column('positions', 'description',
               existing_type=sa.TEXT(),
               comment='Detailed position role description and responsibilities',
               existing_comment='Detailed position role description',
               existing_nullable=True)
    op.alter_column('positions', 'employment_category',
               existing_type=sa.VARCHAR(length=50),
               comment='Employment category (Permanent, Contract, Temporary, Internship)',
               existing_comment='Employment category',
               existing_nullable=False,
               existing_server_default=sa.text("'Permanent'::character varying"))
    op.alter_column('positions', 'grade',
               existing_type=sa.VARCHAR(length=50),
               comment='Job grade (e.g. G5, Band A)',
               existing_comment='Job grade',
               existing_nullable=True)
    op.alter_column('positions', 'level',
               existing_type=sa.VARCHAR(length=50),
               comment='Job level (e.g. L4, L5, Principal)',
               existing_comment='Job level',
               existing_nullable=True)
    op.alter_column('positions', 'maximum_headcount',
               existing_type=sa.INTEGER(),
               comment='Maximum allowed headcount capacity for this position',
               existing_comment='Maximum allowed headcount capacity',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('positions', 'is_managerial',
               existing_type=sa.BOOLEAN(),
               comment='True if position holds manager/leadership authority',
               existing_comment='True if position holds manager authority',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('positions', 'is_managerial',
               existing_type=sa.BOOLEAN(),
               comment='True if position holds manager authority',
               existing_comment='True if position holds manager/leadership authority',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('positions', 'maximum_headcount',
               existing_type=sa.INTEGER(),
               comment='Maximum allowed headcount capacity',
               existing_comment='Maximum allowed headcount capacity for this position',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('positions', 'level',
               existing_type=sa.VARCHAR(length=50),
               comment='Job level',
               existing_comment='Job level (e.g. L4, L5, Principal)',
               existing_nullable=True)
    op.alter_column('positions', 'grade',
               existing_type=sa.VARCHAR(length=50),
               comment='Job grade',
               existing_comment='Job grade (e.g. G5, Band A)',
               existing_nullable=True)
    op.alter_column('positions', 'employment_category',
               existing_type=sa.VARCHAR(length=50),
               comment='Employment category',
               existing_comment='Employment category (Permanent, Contract, Temporary, Internship)',
               existing_nullable=False,
               existing_server_default=sa.text("'Permanent'::character varying"))
    op.alter_column('positions', 'description',
               existing_type=sa.TEXT(),
               comment='Detailed position role description',
               existing_comment='Detailed position role description and responsibilities',
               existing_nullable=True)
    op.create_table('dummy_products',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name='pk_dummy_products'),
    sa.UniqueConstraint('code', name='uq_dummy_products_code', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_dummy_products_is_deleted', 'dummy_products', ['is_deleted'], unique=False)
    op.create_index('ix_dummy_products_id', 'dummy_products', ['id'], unique=False)
    op.create_table('test_products',
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name='pk_test_products'),
    sa.UniqueConstraint('code', name='uq_test_products_code', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_test_products_is_deleted', 'test_products', ['is_deleted'], unique=False)
    op.create_index('ix_test_products_id', 'test_products', ['id'], unique=False)
    op.drop_index(op.f('ix_approval_histories_performed_by'), table_name='approval_histories')
    op.drop_index(op.f('ix_approval_histories_id'), table_name='approval_histories')
    op.drop_index(op.f('ix_approval_histories_approval_request_id'), table_name='approval_histories')
    op.drop_table('approval_histories')
    op.drop_index(op.f('ix_approval_steps_workflow_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_is_deleted'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_id'), table_name='approval_steps')
    op.drop_index(op.f('ix_approval_steps_approver_role_id'), table_name='approval_steps')
    op.drop_table('approval_steps')
    op.drop_index(op.f('ix_approval_requests_workflow_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_submitted_by'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_is_deleted'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_type'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_entity_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_approval_workflows_name'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_module_name'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_is_deleted'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_code'), table_name='approval_workflows')
    op.drop_table('approval_workflows')
    # ### end Alembic commands ###
