"""phase_v061_implement_stock_ledger_engine

Revision ID: c8a97096a1e6
Revises: '00f4c360a213'
Create Date: 2026-07-30 11:54:42.030155+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a97096a1e6'
down_revision: Union[str, None] = '00f4c360a213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transaction_types',
    sa.Column('code', sa.String(length=50), nullable=False, comment='Unique transaction type code (e.g., OPENING_STOCK)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable transaction type name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of transaction type usage'),
    sa.Column('direction', sa.String(length=20), nullable=False, comment='Inventory movement direction: IN, OUT, TRANSFER, ADJUSTMENT, SYSTEM'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Active transaction type status flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_transaction_types'))
    )
    op.create_index(op.f('ix_inventory_transaction_types_code'), 'inventory_transaction_types', ['code'], unique=True)
    op.create_index(op.f('ix_inventory_transaction_types_id'), 'inventory_transaction_types', ['id'], unique=False)
    op.create_table('inventory_adjustments',
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Reference to Product master record'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Reference to Warehouse facility'),
    sa.Column('location_id', sa.UUID(), nullable=True, comment='Optional reference to sub-storage location'),
    sa.Column('adjustment_type', sa.String(length=50), nullable=False, comment='Adjustment type: Increase or Decrease'),
    sa.Column('reason', sa.String(length=255), nullable=False, comment='Reason or justification for inventory adjustment'),
    sa.Column('expected_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Recorded system balance prior to adjustment'),
    sa.Column('actual_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Physically counted stock quantity'),
    sa.Column('difference', sa.Numeric(precision=18, scale=4), nullable=False, comment='Calculated adjustment difference magnitude (actual - expected)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Adjustment state: Draft, Approved, Applied, Cancelled'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User ID who created the adjustment draft'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='User ID who approved the adjustment proposal'),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when adjustment was approved (UTC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_inventory_adjustments_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_inventory_adjustments_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], name=op.f('fk_inventory_adjustments_location_id_storage_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_adjustments_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_inventory_adjustments_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_adjustments'))
    )
    op.create_index(op.f('ix_inventory_adjustments_id'), 'inventory_adjustments', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_location_id'), 'inventory_adjustments', ['location_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_product_id'), 'inventory_adjustments', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_status'), 'inventory_adjustments', ['status'], unique=False)
    op.create_index(op.f('ix_inventory_adjustments_warehouse_id'), 'inventory_adjustments', ['warehouse_id'], unique=False)
    op.create_table('opening_stocks',
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Reference to Product master record'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Reference to Warehouse facility'),
    sa.Column('location_id', sa.UUID(), nullable=True, comment='Optional reference to sub-storage location'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Initial stock quantity being onboarded'),
    sa.Column('reference_number', sa.String(length=100), nullable=False, comment='Unique reference identifier for opening stock entry'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User ID who created opening stock entry'),
    sa.Column('approved_by', sa.UUID(), nullable=True, comment='User ID who approved opening stock entry'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_opening_stocks_approved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_opening_stocks_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['storage_locations.id'], name=op.f('fk_opening_stocks_location_id_storage_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_opening_stocks_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_opening_stocks_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opening_stocks'))
    )
    op.create_index(op.f('ix_opening_stocks_id'), 'opening_stocks', ['id'], unique=False)
    op.create_index(op.f('ix_opening_stocks_location_id'), 'opening_stocks', ['location_id'], unique=False)
    op.create_index(op.f('ix_opening_stocks_product_id'), 'opening_stocks', ['product_id'], unique=False)
    op.create_index(op.f('ix_opening_stocks_reference_number'), 'opening_stocks', ['reference_number'], unique=True)
    op.create_index(op.f('ix_opening_stocks_warehouse_id'), 'opening_stocks', ['warehouse_id'], unique=False)
    op.create_table('stock_balances',
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Reference to Product master record'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Reference to Warehouse facility'),
    sa.Column('storage_location_id', sa.UUID(), nullable=True, comment='Optional reference to sub-storage location'),
    sa.Column('available_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Available physical stock quantity'),
    sa.Column('reserved_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Reserved stock quantity for pending allocations'),
    sa.Column('damaged_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Damaged or non-usable stock quantity'),
    sa.Column('in_transit_quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Stock quantity currently in transit between locations'),
    sa.Column('last_calculated', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when projection balance was last refreshed from ledger'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_balances_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], name=op.f('fk_stock_balances_storage_location_id_storage_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_balances_warehouse_id_warehouses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_balances')),
    sa.UniqueConstraint('product_id', 'warehouse_id', 'storage_location_id', name='uq_stock_balance_prod_wh_loc')
    )
    op.create_index(op.f('ix_stock_balances_id'), 'stock_balances', ['id'], unique=False)
    op.create_index(op.f('ix_stock_balances_product_id'), 'stock_balances', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_storage_location_id'), 'stock_balances', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_stock_balances_warehouse_id'), 'stock_balances', ['warehouse_id'], unique=False)
    op.create_table('stock_ledgers',
    sa.Column('product_id', sa.UUID(), nullable=False, comment='Reference to Product master record'),
    sa.Column('warehouse_id', sa.UUID(), nullable=False, comment='Reference to Warehouse facility'),
    sa.Column('storage_location_id', sa.UUID(), nullable=True, comment='Optional reference to sub-storage location (Rack/Shelf/Bin)'),
    sa.Column('transaction_type_id', sa.UUID(), nullable=False, comment='Reference to InventoryTransactionType'),
    sa.Column('reference_type', sa.String(length=100), nullable=True, comment='Upstream document or module type (e.g. OpeningStock, InventoryAdjustment)'),
    sa.Column('reference_id', sa.UUID(), nullable=True, comment='Upstream document or record UUID'),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), nullable=False, comment='Quantity of stock moved (always positive magnitude)'),
    sa.Column('unit_id', sa.UUID(), nullable=True, comment='Unit of Measure for the transaction quantity'),
    sa.Column('direction', sa.String(length=20), nullable=False, comment='Direction of movement: IN, OUT, TRANSFER, ADJUSTMENT, SYSTEM'),
    sa.Column('running_balance', sa.Numeric(precision=18, scale=4), nullable=False, comment='Calculated total running balance for product at target warehouse after movement'),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False, comment='Effective date and time of transaction (UTC)'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='Remarks or justification notes'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='User ID who executed the inventory movement'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_ledgers_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_ledgers_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storage_location_id'], ['storage_locations.id'], name=op.f('fk_stock_ledgers_storage_location_id_storage_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transaction_type_id'], ['inventory_transaction_types.id'], name=op.f('fk_stock_ledgers_transaction_type_id_inventory_transaction_types'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['unit_id'], ['unit_of_measures.id'], name=op.f('fk_stock_ledgers_unit_id_unit_of_measures'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_stock_ledgers_warehouse_id_warehouses'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_ledgers'))
    )
    op.create_index(op.f('ix_stock_ledgers_id'), 'stock_ledgers', ['id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_product_id'), 'stock_ledgers', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_reference_id'), 'stock_ledgers', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_reference_type'), 'stock_ledgers', ['reference_type'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_storage_location_id'), 'stock_ledgers', ['storage_location_id'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_transaction_date'), 'stock_ledgers', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_stock_ledgers_transaction_type_id'), 'stock_ledgers', ['transaction_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_ledgers_warehouse_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_transaction_type_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_transaction_date'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_storage_location_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_reference_type'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_reference_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_product_id'), table_name='stock_ledgers')
    op.drop_index(op.f('ix_stock_ledgers_id'), table_name='stock_ledgers')
    op.drop_table('stock_ledgers')
    op.drop_index(op.f('ix_stock_balances_warehouse_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_storage_location_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_product_id'), table_name='stock_balances')
    op.drop_index(op.f('ix_stock_balances_id'), table_name='stock_balances')
    op.drop_table('stock_balances')
    op.drop_index(op.f('ix_opening_stocks_warehouse_id'), table_name='opening_stocks')
    op.drop_index(op.f('ix_opening_stocks_reference_number'), table_name='opening_stocks')
    op.drop_index(op.f('ix_opening_stocks_product_id'), table_name='opening_stocks')
    op.drop_index(op.f('ix_opening_stocks_location_id'), table_name='opening_stocks')
    op.drop_index(op.f('ix_opening_stocks_id'), table_name='opening_stocks')
    op.drop_table('opening_stocks')
    op.drop_index(op.f('ix_inventory_adjustments_warehouse_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_status'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_product_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_location_id'), table_name='inventory_adjustments')
    op.drop_index(op.f('ix_inventory_adjustments_id'), table_name='inventory_adjustments')
    op.drop_table('inventory_adjustments')
    op.drop_index(op.f('ix_inventory_transaction_types_id'), table_name='inventory_transaction_types')
    op.drop_index(op.f('ix_inventory_transaction_types_code'), table_name='inventory_transaction_types')
    op.drop_table('inventory_transaction_types')
    # ### end Alembic commands ###
