"""phase_v053_implement_payroll_engine

Revision ID: ec95e52571cb
Revises: 'a3cad77f4bbb'
Create Date: 2026-07-27 14:27:49.419657+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec95e52571cb'
down_revision: Union[str, None] = 'a3cad77f4bbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_periods',
    sa.Column('period_code', sa.String(length=50), nullable=False, comment='Unique payroll period code identifier (e.g. 2026-01, PAY_2026_01)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='Start date of the payroll period'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='End date of the payroll period'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Period processing status: Draft, Processing, Completed, Locked'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_periods'))
    )
    op.create_index(op.f('ix_payroll_periods_id'), 'payroll_periods', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_periods_period_code'), 'payroll_periods', ['period_code'], unique=True)
    op.create_index(op.f('ix_payroll_periods_status'), 'payroll_periods', ['status'], unique=False)
    op.create_table('payroll_records',
    sa.Column('payroll_period_id', sa.UUID(), nullable=False, comment='Foreign Key referencing parent PayrollPeriod'),
    sa.Column('employee_id', sa.UUID(), nullable=False, comment='Foreign Key referencing target Employee'),
    sa.Column('employee_compensation_id', sa.UUID(), nullable=False, comment='Foreign Key referencing active EmployeeCompensation snapshot'),
    sa.Column('working_days', sa.Integer(), nullable=False, comment='Total schedule working days in period'),
    sa.Column('present_days', sa.Numeric(precision=5, scale=2), nullable=False, comment='Total attendance present days'),
    sa.Column('leave_days', sa.Numeric(precision=5, scale=2), nullable=False, comment='Total approved leave days'),
    sa.Column('paid_leave_days', sa.Numeric(precision=5, scale=2), nullable=False, comment='Total paid leave days'),
    sa.Column('unpaid_leave_days', sa.Numeric(precision=5, scale=2), nullable=False, comment='Total unpaid leave (LWP) days'),
    sa.Column('overtime_hours', sa.Numeric(precision=8, scale=2), nullable=False, comment='Overtime hours worked (future ready)'),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False, comment='Gross salary amount before deductions'),
    sa.Column('total_earnings', sa.Numeric(precision=12, scale=2), nullable=False, comment='Sum of all earning component amounts'),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False, comment='Sum of all deduction component amounts'),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False, comment='Calculated Net Salary (Gross - Total Deductions)'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Payroll record status: Draft, Calculated, Approved, Paid'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['employee_compensation_id'], ['employee_compensations.id'], name=op.f('fk_payroll_records_employee_compensation_id_employee_compensations'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name=op.f('fk_payroll_records_employee_id_employees'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payroll_period_id'], ['payroll_periods.id'], name=op.f('fk_payroll_records_payroll_period_id_payroll_periods'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_records')),
    sa.UniqueConstraint('payroll_period_id', 'employee_id', name='uq_period_employee_payroll')
    )
    op.create_index(op.f('ix_payroll_records_employee_compensation_id'), 'payroll_records', ['employee_compensation_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_employee_id'), 'payroll_records', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_id'), 'payroll_records', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_records_payroll_period_id'), 'payroll_records', ['payroll_period_id'], unique=False)
    op.create_index(op.f('ix_payroll_records_status'), 'payroll_records', ['status'], unique=False)
    op.create_table('payroll_record_components',
    sa.Column('payroll_record_id', sa.UUID(), nullable=False, comment='Foreign Key referencing parent PayrollRecord'),
    sa.Column('salary_component_id', sa.UUID(), nullable=False, comment='Foreign Key referencing source SalaryComponent'),
    sa.Column('component_name', sa.String(length=100), nullable=False, comment='Snapshot name of the component'),
    sa.Column('component_type', sa.String(length=50), nullable=False, comment='Component category: Earning, Deduction'),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False, comment='Calculated component amount for the period'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.ForeignKeyConstraint(['payroll_record_id'], ['payroll_records.id'], name=op.f('fk_payroll_record_components_payroll_record_id_payroll_records'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['salary_component_id'], ['salary_components.id'], name=op.f('fk_payroll_record_components_salary_component_id_salary_components'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payroll_record_components'))
    )
    op.create_index(op.f('ix_payroll_record_components_id'), 'payroll_record_components', ['id'], unique=False)
    op.create_index(op.f('ix_payroll_record_components_payroll_record_id'), 'payroll_record_components', ['payroll_record_id'], unique=False)
    op.create_index(op.f('ix_payroll_record_components_salary_component_id'), 'payroll_record_components', ['salary_component_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_record_components_salary_component_id'), table_name='payroll_record_components')
    op.drop_index(op.f('ix_payroll_record_components_payroll_record_id'), table_name='payroll_record_components')
    op.drop_index(op.f('ix_payroll_record_components_id'), table_name='payroll_record_components')
    op.drop_table('payroll_record_components')
    op.drop_index(op.f('ix_payroll_records_status'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_payroll_period_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_employee_id'), table_name='payroll_records')
    op.drop_index(op.f('ix_payroll_records_employee_compensation_id'), table_name='payroll_records')
    op.drop_table('payroll_records')
    op.drop_index(op.f('ix_payroll_periods_status'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_period_code'), table_name='payroll_periods')
    op.drop_index(op.f('ix_payroll_periods_id'), table_name='payroll_periods')
    op.drop_table('payroll_periods')
    # ### end Alembic commands ###
