"""phase_hr5_implement_hr_configurations_table

Revision ID: f3515986f924
Revises: '7178a901bcde'
Create Date: 2026-07-26 16:25:44.144429+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3515986f924'
down_revision: Union[str, None] = '7178a901bcde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hr_configurations',
    sa.Column('organization_name', sa.String(length=150), nullable=False, comment='Official organization name'),
    sa.Column('organization_code', sa.String(length=50), nullable=False, comment='Unique identifier code for organization'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment='Default IANA timezone name (e.g. Asia/Kolkata, UTC)'),
    sa.Column('country', sa.String(length=50), nullable=False, comment='Country of primary enterprise operation'),
    sa.Column('currency', sa.String(length=10), nullable=False, comment='Primary currency ISO code (e.g. INR, USD, EUR)'),
    sa.Column('standard_working_hours_per_day', sa.Float(), nullable=False, comment='Standard expected daily working hours'),
    sa.Column('standard_working_days_per_week', sa.Integer(), nullable=False, comment='Standard expected weekly working days'),
    sa.Column('weekend_configuration', sa.JSON(), nullable=False, comment="JSON list of non-working weekend days (e.g. ['Saturday', 'Sunday'])"),
    sa.Column('default_shift_name', sa.String(length=100), nullable=False, comment='Default enterprise work shift label'),
    sa.Column('grace_period_minutes', sa.Integer(), nullable=False, comment='Allowed late arrival grace period in minutes'),
    sa.Column('minimum_working_hours', sa.Float(), nullable=False, comment='Minimum required hours for half-day credit'),
    sa.Column('default_probation_period_days', sa.Integer(), nullable=False, comment='Default employee probation duration in days'),
    sa.Column('leave_year_start_month', sa.Integer(), nullable=False, comment='Month (1-12) when annual leave quota resets'),
    sa.Column('payroll_cycle', sa.String(length=50), nullable=False, comment='Enterprise payroll frequency (Monthly, Biweekly, Weekly)'),
    sa.Column('fiscal_year_start_month', sa.Integer(), nullable=False, comment='Month (1-12) marking fiscal year start'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Flag indicating active configuration status'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Primary Key UUID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last update timestamp (UTC)'),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False, comment='Soft deletion flag'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted (UTC)'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_hr_configurations'))
    )
    op.create_index(op.f('ix_hr_configurations_id'), 'hr_configurations', ['id'], unique=False)
    op.create_index(op.f('ix_hr_configurations_is_active'), 'hr_configurations', ['is_active'], unique=False)
    op.create_index(op.f('ix_hr_configurations_is_deleted'), 'hr_configurations', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hr_configurations_organization_code'), 'hr_configurations', ['organization_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hr_configurations_organization_code'), table_name='hr_configurations')
    op.drop_index(op.f('ix_hr_configurations_is_deleted'), table_name='hr_configurations')
    op.drop_index(op.f('ix_hr_configurations_is_active'), table_name='hr_configurations')
    op.drop_index(op.f('ix_hr_configurations_id'), table_name='hr_configurations')
    op.drop_table('hr_configurations')
    # ### end Alembic commands ###
